[project]
name = "cable"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "equinox>=0.13.4",
    "jax[cuda13]>=0.9.0.1",
    "jaxtyping>=0.3.9",
    "optax>=0.2.7",
    "scikit-learn>=1.8.0",
]
